name: classicist-sanctuary

services:
  sanctuary-api:
    image: us-west1-docker.pkg.dev/solheim-project/sanctuary/api:latest
    restart: unless-stopped

  sanctuary-web:
    image: us-west1-docker.pkg.dev/solheim-project/sanctuary/web:latest
    ports:
      - '8080:80'
    restart: unless-stopped
