apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
  labels:
    cloud.googleapis.com/location: us-west1
  name: classicist-sanctuary
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
      labels:
        app-version: '${APP_VERSION}'
    spec:
      containerConcurrency: 80
      containers:
        - env:
            - name: LIBSQL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: 'latest'
                  name: LIBSQL_AUTH_TOKEN
            - name: LIBSQL_URL
              valueFrom:
                secretKeyRef:
                  key: 'latest'
                  name: LIBSQL_URL
          image: ${API_IMAGE_REF}
          name: sanctuary-api
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
        - image: ${WEB_IMAGE_REF}
          name: sanctuary-web
          ports:
            - containerPort: 80
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
      serviceAccountName: ${SERVICE_ACCOUNT_EMAIL}
      timeoutSeconds: 300
