import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface PromptOptions {
  topic: string;
  targetLineCount: number;
  originalPoemTitle?: string;
}

const TOLERANCE_PERCENT = 20;

function calculateTolerance(target: number): { min: number; max: number } {
  const min = Math.floor(target * (1 - TOLERANCE_PERCENT / 100));
  const max = Math.ceil(target * (1 + TOLERANCE_PERCENT / 100));
  return { min, max };
}

export function buildPrompt(options: PromptOptions): string {
  const { topic, targetLineCount, originalPoemTitle } = options;
  const { min, max } = calculateTolerance(targetLineCount);

  const basePrompt = `Write an original poem about "${topic}"`;

  const lineCountInstruction = `
The poem must be between ${min} and ${max} lines (target: ${targetLineCount} lines, ±${TOLERANCE_PERCENT}% tolerance).
Do not include line numbers or stanza markers in your response.`;

  const formatInstruction = `
Respond ONLY with valid JSON in the following format:
{
  "title": "Your poem title",
  "content": "The full poem text with line breaks represented as \\n"
}`;

  const styleInstruction = `
Write in a literary, evocative style. Avoid clichés and generic phrases.
The poem should feel like it was written by a human poet, not generated by AI.
Use concrete imagery, sensory details, and emotional resonance.`;

  let prompt = basePrompt + lineCountInstruction + formatInstruction + styleInstruction;

  if (originalPoemTitle) {
    prompt += `\n\nThis poem is inspired by/related to: "${originalPoemTitle}".`;
  }

  return prompt;
}

export function loadSystemInstructions(): string {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const systemInstructionsPath = resolve(__dirname, '../prompts/system-instructions.md');

  try {
    return readFileSync(systemInstructionsPath, 'utf-8');
  } catch {
    return getDefaultSystemInstructions();
  }
}

function getDefaultSystemInstructions(): string {
  return `You are a creative poet writing original poems.

Your task is to write high-quality, original poetry that sounds authentically human.

Guidelines:
- Write in your own voice, not as an AI assistant
- Use vivid, concrete imagery rather than abstract concepts
- Employ varied line lengths and rhythm
- Create emotional resonance through specific details
- Avoid generic AI phrases like "Here is a poem" or "I hope you enjoy"
- Never include meta-commentary about being an AI

Output format:
Return ONLY valid JSON with "title" and "content" fields.
Use \\n for line breaks in the content field.`;
}
