import React, { useId } from 'react';
import { AuthorType, sanitizeExternalHttpUrl } from '@sanctuary/shared';
import type { SourceInfo as SourceInfoData } from '@sanctuary/shared';

interface SourceInfoProps {
  idPrefix?: string;
  author: string;
  type: AuthorType;
  year?: string;
  sourceInfo?: SourceInfoData;
}

export const SourceInfo: React.FC<SourceInfoProps> = ({
  idPrefix,
  author,
  type,
  year,
  sourceInfo,
}) => {
  const isHuman = type === AuthorType.HUMAN;
  const authorColor = isHuman ? 'text-seal-red' : 'text-binding-blue';
  const reactId = useId();
  const baseId = idPrefix ?? `source-info-${reactId.replace(/:/g, '')}`;
  const safeSourceUrl = sanitizeExternalHttpUrl(sourceInfo?.primary.sourceUrl);

  return (
    <div id={`${baseId}-container`} className="text-left space-y-0.5">
      <p
        id={`${baseId}-label`}
        className="font-sans text-[10px] tracking-[0.15em] uppercase font-medium text-pencil"
      >
        {isHuman ? 'Human Author' : 'AI Author'}
      </p>
      <p id={`${baseId}-author`} className={`font-serif font-bold text-base italic ${authorColor}`}>
        {isHuman ? `Written by ${author}` : `Generated by ${author}`}
      </p>
      {isHuman && year && (
        <p id={`${baseId}-year`} className="font-sans text-xs text-pencil/70">
          {year}
        </p>
      )}
      {isHuman && sourceInfo?.primary.source && (
        <p id={`${baseId}-source`} className="font-sans text-xs text-pencil/60">
          {safeSourceUrl ? (
            <a
              id={`${baseId}-source-link`}
              href={safeSourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2 hover:text-ink transition-colors"
            >
              {sourceInfo.primary.source}
            </a>
          ) : (
            sourceInfo.primary.source
          )}
        </p>
      )}
    </div>
  );
};
