import React from 'react';
import { AuthorType } from '@sanctuary/shared';
import type { SourceInfo as SourceInfoData } from '@sanctuary/shared';

interface SourceInfoProps {
  author: string;
  type: AuthorType;
  year?: string;
  sourceInfo?: SourceInfoData;
}

export const SourceInfo: React.FC<SourceInfoProps> = ({ author, type, year, sourceInfo }) => {
  const isHuman = type === AuthorType.HUMAN;
  const authorColor = isHuman ? 'text-seal-red' : 'text-binding-blue';

  return (
    <div className="text-left space-y-0.5">
      <p className="font-sans text-[10px] tracking-[0.15em] uppercase font-medium text-pencil">
        {isHuman ? 'Human Author' : 'AI Author'}
      </p>
      <p className={`font-serif font-bold text-base italic ${authorColor}`}>
        {isHuman ? `Written by ${author}` : `Generated by ${author}`}
      </p>
      {isHuman && year && <p className="font-sans text-xs text-pencil/70">{year}</p>}
      {isHuman && sourceInfo?.primary.source && (
        <p className="font-sans text-xs text-pencil/60">
          {sourceInfo.primary.sourceUrl ? (
            <a
              href={sourceInfo.primary.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2 hover:text-ink transition-colors"
            >
              {sourceInfo.primary.source}
            </a>
          ) : (
            sourceInfo.primary.source
          )}
        </p>
      )}
    </div>
  );
};
